services:
  menotaai-web:
    build:
      context: src\.
      dockerfile: Dockerfile
    container_name: menotaai-web
    hostname: menotaai-web-host
    ports:
    - "5003:8080"
    networks:
      - menotaai_network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=menotaai-db;Database=VisitantesDb;Username=postgres;Password=Losk0707
    depends_on:
      - menotaai-db

  menotaai-db:
    image: postgres:17.2
    command: postgres -c max_connections=1000
    container_name: menotaai-db
    hostname: menotaai-db
    environment:
      - POSTGRES_DB=VisitantesDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Losk0707
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - menotaai_network

networks:
  menotaai_network:

volumes:
    pgdata: